# Generated by Django 5.2.3 on 2025-10-10 09:04

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='Sinf nomi')),
                ('grade_level', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(11)], verbose_name='Sinf darajasi')),
                ('section', models.CharField(max_length=5, verbose_name="Bo'lim")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sinf',
                'verbose_name_plural': 'Sinflar',
                'ordering': ['grade_level', 'section'],
            },
        ),
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kriteriya nomi')),
                ('max_score', models.PositiveIntegerField(verbose_name='Maksimal ball')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol kriteriya')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
            ],
            options={
                'verbose_name': 'Kriteriya',
                'verbose_name_plural': 'Kriteriyalar',
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, verbose_name='Izoh')),
                ('week_number', models.IntegerField(verbose_name='Hafta raqami')),
                ('month', models.IntegerField(default=10, verbose_name='Oy')),
                ('year', models.IntegerField(default=2025, verbose_name='Yil')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
            ],
            options={
                'verbose_name': 'Baholash',
                'verbose_name_plural': 'Baholashlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Kalit')),
                ('value', models.TextField(verbose_name='Qiymat')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tizim sozlamasi',
                'verbose_name_plural': 'Tizim sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('teacher', "O'qituvchi"), ('manager', 'Menejer')], default='teacher', max_length=10)),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiya')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodimlar',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ball')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.criterion', verbose_name='Kriteriya')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='main_app.evaluation', verbose_name='Baholash')),
            ],
            options={
                'verbose_name': 'Baholash natijasi',
                'verbose_name_plural': 'Baholash natijalari',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiya')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name="O'quvchi ID")),
                ('date_of_birth', models.DateField(verbose_name="Tug'ilgan sana")),
                ('parent_phone', models.CharField(blank=True, max_length=15, verbose_name='Ota-ona telefoni')),
                ('image', models.ImageField(blank=True, null=True, upload_to='students_photo/')),
                ('enrollment_date', models.DateField(default=django.utils.timezone.now, verbose_name="Ro'yxatga olingan sana")),
                ('class_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='main_app.class', verbose_name='Sinf')),
            ],
            options={
                'verbose_name': "O'quvchi",
                'verbose_name_plural': "O'quvchilar",
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(verbose_name='Ota-onasining telegram ID si')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.student', verbose_name="O'quvchi")),
            ],
            options={
                'verbose_name': 'Ota-ona',
                'verbose_name_plural': 'Ota-onalar',
            },
        ),
        migrations.AddField(
            model_name='evaluation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='main_app.student', verbose_name="O'quvchi"),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=17, verbose_name='Telefon raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('image', models.ImageField(blank=True, null=True, upload_to='teachers_photo/')),
                ('hire_date', models.DateField(default=django.utils.timezone.now, verbose_name='Ishga qabul qilingan sana')),
                ('class_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.class', verbose_name='Tayinlangan sinf')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "O'qituvchi",
                'verbose_name_plural': "O'qituvchilar",
            },
        ),
        migrations.AddField(
            model_name='evaluation',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='main_app.teacher', verbose_name="O'qituvchi"),
        ),
        migrations.CreateModel(
            name='StudentMonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(verbose_name='Oy')),
                ('year', models.IntegerField(default=2025, verbose_name='Yil')),
                ('total_evaluations', models.IntegerField(verbose_name='Baholashlar soni')),
                ('average_score', models.FloatField(verbose_name="O'rtacha ball")),
                ('highest_score', models.FloatField(blank=True, null=True, verbose_name='Eng yuqori ball')),
                ('lowest_score', models.FloatField(blank=True, null=True, verbose_name='Eng past ball')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_reports', to='main_app.student', verbose_name="O'quvchi")),
            ],
            options={
                'verbose_name': "O'quvchi oylik hisobot",
                'verbose_name_plural': "O'quvchilar oylik hisobotlari",
                'ordering': ['-year', '-month'],
                'unique_together': {('student', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(verbose_name='Oy')),
                ('year', models.IntegerField(default=2025, verbose_name='Yil')),
                ('total_students', models.IntegerField(verbose_name="Jami o'quvchilar")),
                ('evaluated_students', models.IntegerField(verbose_name="Baholangan o'quvchilar")),
                ('average_score', models.FloatField(verbose_name="O'rtacha ball")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.class', verbose_name='Sinf')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.teacher', verbose_name="O'qituvchi")),
            ],
            options={
                'verbose_name': 'Oylik hisobot',
                'verbose_name_plural': 'Oylik hisobotlar',
                'ordering': ['-year', '-month'],
                'unique_together': {('class_assigned', 'teacher', 'month', 'year')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='evaluation',
            unique_together={('student', 'teacher', 'week_number', 'year')},
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField(verbose_name='Hafta raqami')),
                ('year', models.IntegerField(default=2025, verbose_name='Yil')),
                ('total_students', models.IntegerField(verbose_name="Jami o'quvchilar")),
                ('evaluated_students', models.IntegerField(verbose_name="Baholangan o'quvchilar")),
                ('average_score', models.FloatField(verbose_name="O'rtacha ball")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.class', verbose_name='Sinf')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.teacher', verbose_name="O'qituvchi")),
            ],
            options={
                'verbose_name': 'Haftalik hisobot',
                'verbose_name_plural': 'Haftalik hisobotlar',
                'ordering': ['-year', '-week_number'],
                'unique_together': {('class_assigned', 'teacher', 'week_number', 'year')},
            },
        ),
    ]
